export const colorSets = {
  pink: {
    primary: 'text-pink-600',
    secondary: 'text-pink-300',
    // tertiary: 'green-500',
    // quaternary: 'orange-500',
    barHover: 'hover:bg-pink-400',
    bg: 'bg-pink-500',
    borderButton: 'border-pink-600',
  },
  sky: {
    primary: 'text-sky-600',
    secondary: 'text-sky-300',
    // tertiary: 'cyan-500',
    // quaternary: 'purple-500',
    barHover: 'hover:bg-sky-400',
    bg: 'bg-sky-500',
    borderButton: 'border-sky-600',
  },
  green: {
    primary: 'text-green-600',
    secondary: 'text-green-300',
    // tertiary: 'sky-500',
    // quaternary: 'orange-500',
    barHover: 'hover:bg-green-400',
    bg: 'bg-green-500',
    borderButton: 'border-green-600',
  },
  orange: {
    primary: 'text-orange-600',
    secondary: 'text-orange-300',
    // tertiary: 'green-500',
    // quaternary: 'blue-500',
    barHover: 'hover:bg-orange-400',
    bg: 'bg-orange-500',
    borderButton: 'border-orange-600',
  },
  white: {
    primary: 'text-white',
    secondary: 'text-white',
    // tertiary: 'green-500',
    // quaternary: 'blue-500',
    barHover: 'hover:bg-gray-400',
    bg: 'bg-gray-800',
    borderButton: 'border-white',
  }
};