import "~/styles/globals.css";
import { ColorProvider } from "~/lib/colorContext";
import {Providers} from "./providers";
import { TopNav } from "~/components/topNav";


export const metadata = {
  title: "CodX",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
}) {
  return (
      <ColorProvider>
        <html lang="en">
          <body className={`h-screen w-full flex justify-center bg-slate-950`}>
            <Providers>
              <TopNav />
              <main className="w-full h-full flex justify-center">
                {children}
                {auth}
                <div id="modal-root" />
              </main>
            </Providers>
          </body>
        </html>
      </ColorProvider>
  );
}
