import "~/styles/globals.css";
import { ColorProvider } from "~/components/colorContext";

export const metadata = {
  title: "CodX",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ColorProvider>
      <html lang="en">
        <body className={`relative h-full w-screen bg-slate-950`}>
          <div className="absolute w-full h-screen bottom-0 left-0 right-0 top-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:14px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]"></div>
            {children}
        </body>
      </html>
    </ColorProvider>
  );
}
