import "~/styles/globals.css";
import { ColorProvider } from "~/lib/colorContext";

export const metadata = {
  title: "CodX",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ColorProvider>
      <html lang="en">
        <body className={`relative h-[1000px] w-screen bg-slate-950`}>
          {children}
        </body>
      </html>
    </ColorProvider>
  );
}
